### ISSUE TITLE
Cats are stuck on one platform (Level 4)

### ISSUE THREAD

**Issue by jennyyi78** [Code4Community/cats-and-mice#37]

**Comment by kylemw1133** [comment]
// row 1 platforms
  platForm11 = this.add.tileSprite(0, 100, 360, 16, "ground");
  platForm12 = this.add.tileSprite(420, 130, 400, 16, "ground");
  platForm13 = this.add.tileSprite(860, 160, 400, 16, "ground");
  // row 2 platforms
  platForm21 = this.add.tileSprite(1300, 280, 360, 16, "ground");
  platForm22 = this.add.tileSprite(880, 310, 400, 16, "ground");
  platForm23 = this.add.tileSprite(440, 340, 400, 16, "ground");
  //row 3 platforms
  platForm31 = this.add.tileSprite(0, 460, 360, 16, "ground");
  platForm32 = this.add.tileSprite(425, 500, 400, 16, "ground");
  platForm33 = this.add.tileSprite(840, 550, 400, 16, "ground");

  platforms.add(platForm11);
  platforms.add(platForm12);
  platforms.add(platForm13);
  platforms.add(platForm21);
  platforms.add(platForm22);
  platforms.add(platForm23);
  platforms.add(platForm31);
  platforms.add(platForm32);
  platforms.add(platForm33);
